name: Upload Test Artifact

on:
  workflow_dispatch:

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Create dummy file
        run: echo "test" > test.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: test.txt
